name             'testweb'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures testweb'
long_description 'Installs/Configures testweb'
version          '0.1.0'

depends		'apt'
depends		'nginx'